name: Sync Movidesk → Neon / Histórico de Status
on:
  workflow_dispatch:

jobs:
  sync_status_history:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install -r requirements.txt

      - run: |
          psql "$NEON_DSN" <<EOF
          CREATE SCHEMA IF NOT EXISTS visualizacao_resolucao;
          CREATE TABLE IF NOT EXISTS visualizacao_resolucao.resolucao_por_status (
            ticket_id                         INTEGER   NOT NULL,
            status                            TEXT      NOT NULL,
            justificativa                     TEXT      NOT NULL,
            seconds_utl                       INTEGER,
            permanency_time_fulltime_seconds DOUBLE PRECISION,
            changed_by                        JSONB,
            changed_date                      TIMESTAMP,
            agent_name                        TEXT,
            team_name                         TEXT,
            imported_at                       TIMESTAMP DEFAULT NOW(),
            PRIMARY KEY(ticket_id, status, justificativa)
          );
          EOF
        env:
          NEON_DSN: ${{ secrets.NEON_DSN }}

      - run: python sync_status_history.py
        env:
          MOVIDESK_TOKEN: ${{ secrets.MOVIDESK_TOKEN }}
          NEON_DSN:       ${{ secrets.NEON_DSN }}
