name: Sync Movidesk -> Neon / Resolução

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run DB migrations
        env:
          NEON_DSN: ${{ secrets.NEON_DSN }}
        run: |
          psql "$NEON_DSN" <<EOF
          CREATE SCHEMA IF NOT EXISTS visualizacao_resolucao;
          CREATE TABLE IF NOT EXISTS visualizacao_resolucao.movidesk_resolution (
            ticket_id   INTEGER   NOT NULL,
            protocol    TEXT,
            resolved_in TIMESTAMP NOT NULL,
            net_hours   NUMERIC,
            imported_at TIMESTAMP DEFAULT NOW(),
            PRIMARY KEY(ticket_id, resolved_in)
          );
          EOF

      - name: Run sync script
        env:
          MOVIDESK_TOKEN: ${{ secrets.MOVIDESK_TOKEN }}
          NEON_DSN:       ${{ secrets.NEON_DSN }}
        run: python sync_resolution_time.py
