name: Sync Movidesk → Neon / Histórico de Status

on:
  workflow_dispatch:
    inputs:
      ticket_id:
        description: 'ID do ticket para teste'
        required: true

jobs:
  sync_status_history:
    runs-on: ubuntu-latest
    env:
      MOVIDESK_TOKEN: ${{ secrets.MOVIDESK_TOKEN }}
      NEON_DSN:       ${{ secrets.NEON_DSN }}
      TICKET_ID:      ${{ github.event.inputs.ticket_id }}
    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Garantir tabela existe
        run: |
          psql "$NEON_DSN" <<EOF
          CREATE SCHEMA IF NOT EXISTS visualizacao_resolucao;
          CREATE TABLE IF NOT EXISTS visualizacao_resolucao.resolucao_por_status (
            ticket_id                         INTEGER   NOT NULL,
            status                            TEXT      NOT NULL,
            justificativa                     TEXT      NOT NULL,
            seconds_utl                       INTEGER,
            permanency_time_fulltime_seconds DOUBLE PRECISION,
            agent_name                        TEXT      NOT NULL,
            team_name                         TEXT      NOT NULL,
            changed_date                      TIMESTAMP,
            imported_at                       TIMESTAMP DEFAULT NOW(),
            PRIMARY KEY(ticket_id, status, justificativa)
          );
          EOF

      - name: Sync histórico de status
        run: python sync_status_history.py
