name: Sync Movidesk → Neon / Histórico de Status

on:
  workflow_dispatch:
    inputs:
      ticket_id:
        description: 'ID do ticket para teste'
        required: true

jobs:
  sync_status_history:
    runs-on: ubuntu-latest
    env:
      MOVIDESK_TOKEN: ${{ secrets.MOVIDESK_TOKEN }}
      NEON_DSN:       ${{ secrets.NEON_DSN }}
      TICKET_ID:      ${{ github.event.inputs.ticket_id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Ensure tabela e colunas existam
        run: |
          psql "$NEON_DSN" <<EOF
          CREATE SCHEMA IF NOT EXISTS visualizacao_resolucao;
          CREATE TABLE IF NOT EXISTS visualizacao_resolucao.resolucao_por_status (
            ticket_id                         INTEGER   NOT NULL,
            protocol                          TEXT,
            status                            TEXT      NOT NULL,
            justificativa                     TEXT      NOT NULL,
            seconds_utl                       INTEGER,
            permanency_time_fulltime_seconds DOUBLE PRECISION,
            agent_name                        TEXT,
            team_name                         TEXT,
            changed_date                      TIMESTAMP,
            imported_at                       TIMESTAMP DEFAULT NOW(),
            PRIMARY KEY(ticket_id, status, justificativa)
          );
          EOF

      - name: Sync histórico de status
        run: python sync_status_history.py
