name: Sync Movidesk -> Neon / Histórico de Status

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  sync_status_history:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Ensure schema & table exist
        env:
          NEON_DSN: ${{ secrets.NEON_DSN }}
        run: |
          psql "$NEON_DSN" <<EOF
          CREATE SCHEMA IF NOT EXISTS visualizacao_resolucao;
          CREATE TABLE IF NOT EXISTS visualizacao_resolucao.resolucao_por_status (
            ticket_id                         INTEGER   NOT NULL,
            protocol                          TEXT,
            status                            TEXT      NOT NULL,
            justificativa                     TEXT      NOT NULL,
            seconds_utl                       INTEGER,
            permanency_time_fulltime_seconds DOUBLE PRECISION,
            changed_by                        JSONB,
            changed_date                      TIMESTAMP,
            imported_at                       TIMESTAMP DEFAULT NOW(),
            PRIMARY KEY(ticket_id, status, justificativa)
          );
          EOF

      - name: Sync histórico de status
        env:
          MOVIDESK_TOKEN: ${{ secrets.MOVIDESK_TOKEN }}
          NEON_DSN:       ${{ secrets.NEON_DSN }}
        run: python sync_status_history.py
