name: sync-json
on:
  workflow_dispatch:
    inputs:
      debug_ticket_id:
        description: Ticket para dump completo (opcional)
        required: false
  schedule:
    - cron: "*/30 * * * *"
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests psycopg2-binary
      - env:
          MOVIDESK_TOKEN: ${{ secrets.MOVIDESK_TOKEN }}
          NEON_DSN: ${{ secrets.NEON_DSN }}
          MOVIDESK_DEBUG_TICKET_ID: ${{ inputs.debug_ticket_id }}
        run: python sync_tickets_json.py
