name: Sync Movidesk -> Neon / Histórico de Status (lote)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      MOVIDESK_TOKEN: ${{ secrets.MOVIDESK_TOKEN }}
      NEON_DSN: ${{ secrets.NEON_DSN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: ls -la
      - run: python sync_status_history_batch.py
