name: Sync Movidesk → Neon / Histórico de Status

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
    inputs:
      TICKET_ID:
        description: 'Opcional: ID de ticket para sincronização pontual'
        required: false

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      MOVIDESK_TOKEN: ${{ secrets.MOVIDESK_TOKEN }}
      NEON_DSN:       ${{ secrets.NEON_DSN }}
      # se quiser testar só um ticket, passa via workflow_dispatch input
      TICKET_ID:     ${{ github.event.inputs.TICKET_ID || '' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Ensure schema & table exist
        run: |
          psql "$NEON_DSN" <<EOF
          CREATE SCHEMA IF NOT EXISTS visualizacao_resolucao;
          CREATE TABLE IF NOT EXISTS visualizacao_resolucao.resolucao_por_status (
            ticket_id                         INTEGER   NOT NULL,
            protocol                          TEXT,
            status                            TEXT      NOT NULL,
            justificativa                     TEXT      NOT NULL,
            seconds_utl                       INTEGER,
            permanency_time_fulltime_seconds DOUBLE PRECISION,
            agent_name                        TEXT,
            team_name                         TEXT,
            changed_date                      TIMESTAMP,
            imported_at                       TIMESTAMP DEFAULT NOW(),
            PRIMARY KEY(ticket_id, status, justificativa)
          );
          EOF

      - name: Sync histórico de status
        run: python sync_status_history.py
