name: Sync Agents (Movidesk -> Neon)

on:
  workflow_dispatch:
  schedule:
    - cron: "15 * * * *"   # a cada hora no minuto 15 (ajuste se quiser)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sync_agents.py
        env:
          MOVIDESK_TOKEN: ${{ secrets.MOVIDESK_TOKEN }}
          NEON_POSTGRES_URL: ${{ secrets.NEON_POSTGRES_URL }}
        run: |
          python sync_agents.py
